---
title: ""
---

<div style="text-align: justify">

<br />
    <br />
    
    
### **¿Qué son los DESCA?**

Los Derechos Económicos, Sociales, Culturales y Ambientales [(DESCA)](https://www.ohchr.org/SP/Issues/ESCR/Pages/ESCRIndex.aspx) son los derechos humanos relativos a las condiciones necesarias para un nivel de vida adecuado y fueron proclamados en la [Declaración Universal de los Derechos Humanos](https://www.un.org/es/about-us/universal-declaration-of-human-rights) (1948) y reforzados por el [Pacto Internacional de Derechos Económicos, Sociales y Culturales](https://www.ohchr.org/Documents/ProfessionalInterest/cescr_SP.pdf) (PIDESC) (1966). Incluyen los elementos básicos y necesarios para tener una vida digna, entre los cuales se encuentran alimentación, salud, vivienda, educación, trabajo, seguridad social, cultura y un medio ambiente adecuado.

En 2008, el [Protocolo Facultativo del PIDESC](https://www.ohchr.org/sp/professionalinterest/pages/opcescr.aspx) creó un mecanismo para recibir denuncias a nivel internacional, formalizando y dando carácter vinculante al rol del Comité DESC para recibir y examinar esas comunicaciones que pueden ser realizadas por personas o grupos. El Comité debe examinarlas, proponer medidas provisionales o soluciones amigables, así como realizar observaciones e informes. Con la ratificación del Protocolo, los Estados adquieren obligaciones respecto de los DESCA y reconocen la competencia del Comité en estos aspectos y, por lo tanto, se comprometen a responder las comunicaciones y seguir sus recomendaciones.

La entrada en vigor del Protocolo Facultativo en 2013 permite materializar la idea de que los DESCA generan obligaciones para los Estados a través de la labor de vigilancia del Comité DESC, sumando una garantía para que todas las personas puedan acceder a estos derechos y contar con mecanismos de exigibilidad en caso de que se vulneren. En torno a los DESCA se ha suscitado un importante debate sobre exigibilidad y justiciabilidad, es decir, la posibilidad de exigirle a los Estados el cumplimiento de estos derechos y de reclamarlos ante la justicia [(ver Observación General nº 9 Comité DESC)](https://www.escr-net.org/es/recursos/observacion-general-no-9-aplicacion-interna-del-pacto). 

En este aspecto, usualmente se destacan algunas diferencias entre los derechos civiles y políticos y los DESCA, derivadas de que los primeros son entendidos como “derechos-libertades” -que implican en muchos casos que el Estado se abstenga de actuar- y los segundos son entendidos como “derechos-prestación” -que implican en muchos casos una acción efectiva del Estado para garantizar su cumplimiento-. A pesar de esta extendida diferenciación, debe repararse en que todos los derechos humanos implican obligaciones ya sea de actuar o ya sea de abstenerse a actuar por parte de los Estados. En el caso de los derechos civiles y políticos, en algunos casos los Estados deben realizar una acción efectiva, un ejemplo de ello es la obligación de realizar elecciones periódicas. En el caso de los DESCA, en algunos casos los Estados deben abstenerse de actuar, como por ejemplo para garantizar el derecho de huelga. 

Sin embargo, pese a que tampoco es una división exacta que diferencie a los derechos civiles y políticos de los DESCA, de modo general pueden derivarse algunas implicancias de la diferenciación entre “derechos-libertades” y “derechos-prestación”, la cual no está vinculada a la manera en que el Estado debe garantizarlos, sino a las características de los bienes necesarios para efectivizar los derechos. En ese sentido, los derechos civiles y políticos, en general, no representan un área de especial interés para el mercado porque mayoritariamente no se trata de bienes que puedan mercantilizarse. En cambio, los DESCA sí involucran bienes y servicios mercantilizables y que de hecho el mercado ofrece. En ese sentido, exige de los Estados el desarrollo de acciones que involucran una serie de recursos económicos, administrativos y profesionales que se deberán traducir en prestaciones y/o regulaciones. En estos procesos, a la hora de la elaboración de políticas públicas, el Estado no es ajeno a la influencia tanto de quienes reclaman la satisfacción de sus derechos, como de aquellos que buscan preservar sus intereses económicos.

Desde un enfoque de derechos, la pobreza es en sí misma un problema urgente y prioritario de derechos humanos y es a la vez causa y consecuencia de vulneraciones de los derechos de las personas pobres. Al plantear la pobreza y la privación como violaciones de los DESCA se impone al Estado la obligación de prevenir y reparar estas situaciones y al mismo tiempo definir los límites de lo mercantilizable, es decir: _**¿Qué bienes y servicios deben ser distribuidos bajo criterios no mercantiles y cuáles son los mínimos de satisfacción por encima de los cuáles se permite actuar al mercado?**_ En otras palabras _**¿Cuáles son los mínimos prestacionales para considerar que los DESCA se encuentran satisfechos?**_

Dada la naturaleza de estos derechos, para determinar en qué medida los Estados están cumpliendo con sus obligaciones en materia de DESCA, la definición de indicadores y la producción de información de base resultan indispensables para poder establecer la medida del progreso e identificar los desafíos pendientes.

- - -

### **¿Cuáles son los Principios que rigen las obligaciones del Estado que implican los DESCA?**

Los Estados, tienen la obligación de _respetar, proteger y cumplir_ los derechos humanos. Deben _respetar_, en tanto están obligados a no interferir ni violar los derechos humanos de las personas. Deben _proteger_, en tanto están obligados a evitar que terceros -sean personas, organizaciones u otros Estados- interfieran o violen los derechos humanos de las personas dentro de su jurisdicción. Deben _cumplir_, en tanto están obligados a adoptar medidas positivas para garantizar que los derechos humanos sean ejercidos. Esta obligación de cumplimiento tiene variaciones en función de los recursos y capacidades que dispone cada Estado, es por ello que se aplica el principio de _realización progresiva_.

En relación a los DESCA, las constituciones nacionales establecen en muchos casos obligaciones específicas de los Estados. A su vez, la ratificación de la normativa internacional introduce otro conjunto de obligaciones estatales en el orden jurídico nacional, por lo que la aprobación de leyes y reglamentaciones deben guardar acuerdo con los compromisos asumidos. Además, la [Observación General nº 3 del Comité DESC](https://www.escr-net.org/es/recursos/observacion-general-no-3-indole-obligaciones-estados-partes) establece que la estructura normativa y cualquier acción del Estado deben guiarse por una serie de principios, entre los cuales se incluyen los siguientes:

• **Progresividad:** acciones estatales que avancen en la universalización de los derechos.

El concepto de progresividad se introduce con el fin de respetar las distintas situaciones en las que se encuentran los países. No obstante, el Comité puntualiza que esto no debe oficiar como una excusa: “Sin embargo, el hecho de que la efectividad a lo largo del tiempo, o en otras palabras progresivamente, se prevea en relación con el Pacto, no se ha de interpretar equivocadamente como que priva a la obligación de todo contenido significativo” (Observación General n°3, art. 9).

• **No regresividad:** no retroceder en el nivel de bienestar alcanzado. 

Por el principio de no regresividad ninguna norma nueva puede significar un grado de protección menor que la vigente, es decir, no se admiten retrocesos con respecto a la situación anterior. Si esto se prueba, la norma resulta inválida en tanto el Estado no argumente en qué sentido puede ser justificable, a pesar de ser regresiva. En esa explicación, no serán de recibo las razones fundadas en la disciplina fiscal u otro tipo de consideraciones similares, sino que debe demostrarse qué otros derechos económicos, sociales, culturales y ambientales resultaron favorecidos por la medida. En situaciones excepcionales inevitables, la regresividad puede darse únicamente en la medida en que sea necesaria y en todo momento debe orientarse la acción a mitigar las desigualdades que se agudizan en los momentos de crisis, garantizando que los derechos no se vean vulnerados en forma desproporcionada para los grupos más vulnerables.

• **Adopción de medidas:** obligación de adoptar medidas, tanto administrativas, legislativas como económicas.

Como se indica en el párrafo segundo de la Observación General n°3 del Comité DESC, si bien la plena realización de los derechos puede lograrse de manera paulatina, las medidas tendientes a lograr este objetivo deben adoptarse dentro de un plazo razonablemente breve tras la entrada en vigor del Pacto para los Estados interesados. Asimismo, las medidas deben ser deliberadas, concretas y orientadas lo más claramente posible hacia la satisfacción de las obligaciones establecidas en el PIDESC.

• **No discriminación:** asegurar la igualdad formal y sustantiva y deber de remover obstáculos.

El reconocimiento de los DESCA, junto con el principio de no discriminación establecido por el artículo n°2 del PIDESC y desarrollado en la Observación General nº3, establecen que los grupos más excluidos y discriminados deben ser priorizados, en el entendido de que quienes tienen los medios pueden acceder a los bienes y servicios involucrados en los DESCA en el mercado. 

• **Uso del máximo de recursos disponibles:** el Estado tiene el deber de utilizar al máximo los recursos económicos, fiscales y de cooperación internacional.

El Comité DESC señala que los Estados, para cumplir con sus obligaciones, deben disponer “Hasta el máximo de los recursos disponibles, mediante la asistencia y cooperación internacionales”, lo que supone tomar en cuenta tanto recursos existentes dentro de un Estado como los que pone a su disposición la comunidad internacional mediante la cooperación y la asistencia (Observación General n°3, art. 13). En este sentido, los Estados sólo pueden alegar la falta de recursos si demuestran que han realizado todos los esfuerzos posibles. 

- - -

### **¿Cuál es el rol de las Instituciones Nacional de Derechos Humanos en relación a los DESCA?**

El Comité DESC en su [Observación General nº10]( http://docstore.ohchr.org/SelfServices/FilesHandler.ashx?enc=4slQ6QSmlBEDzFEovLCuW%2bKyH%2bnXprasyMzd2e8mx4coF4mDcGIt9z8ZrFOMwRZ4WackdTP3Ipm9AU%2bw%2fk37F4YTtjT8lht5w6uGEiOVOAzsxfspQ3oEdAjKbPIF1rBu) establece que el rol de las INDH es fundamental para el logro progresivo de la plena efectividad de estos derechos. Por tanto, los Estados deben otorgarle a los DESC un lugar destacado en los mandatos que les proporcionan a estas instituciones. En ese documento, se listan los tipos de tareas que las INDH podrían emprender en relación a los DESCA, entre las cuales se incluyen:

•	el fomento de programas de educación e información destinados a mejorar el conocimiento y la comprensión de los derechos económicos, sociales y culturales, tanto entre la población en general como en determinados grupos, por ejemplo, en la administración pública, el poder judicial, el sector privado y el movimiento laboral.

•	el minucioso examen de las leyes y las disposiciones administrativas vigentes, así como de los proyectos de ley y otras propuestas, para cerciorarse de que son compatibles con los requisitos estipulados en el Pacto Internacional de Derechos Económicos, Sociales y Culturales.

•	la prestación de asesoramiento técnico o la realización de estudios en relación con los derechos económicos, sociales y culturales, inclusive a petición de las autoridades públicas o de otras instancias apropiadas.

•	la determinación de criterios nacionales de referencia que permitan medir el grado de cumplimiento de las obligaciones que impone el Pacto.

•	la realización de investigaciones y de estudios con vistas a determinar la medida en que se llevan a la práctica determinados derechos económicos, sociales y culturales, bien sea dentro del Estado en general, o en determinadas esferas o en relación con determinadas comunidades particularmente vulnerables.

•	la vigilancia de la observancia de derechos específicos que se reconocen en el Pacto y la preparación de informes al respecto dirigidos a las autoridades públicas y a la sociedad civil.

•	el examen de las reclamaciones en que se aleguen violaciones de las normas aplicables en materia de derechos económicos, sociales y culturales dentro del Estado.

- - -